### ISSUE TITLE
I receive an issue when i try to run gulp and gulp watch

### ISSUE THREAD

**Issue by alotoftype** [zslabs/basey-theme#7]
I receive the following error when i try to run gulp and gulp watch
 Requiring external module coffee-script/register
module.js:338
    throw err;
          ^
Error: Cannot find module 'lodash'
  at Function.Module._resolveFilename (module.js:336:15)
  at Function.Module._load (module.js:278:25)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/node_modules/globule/lib/globule.js:14:9)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:16:15)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:1:74)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/gulp/node_modules/vinyl-fs/index.js:6:10)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/gulp/index.js:7:11)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Object.<anonymous> (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/gulpfile.coffee:2:15)
  at Object.<anonymous> (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/gulpfile.coffee:2:1)
  at Module._compile (module.js:460:26)
  at Object.loadFile (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Applications/wordpress-4.2.2-0/apps/wordpress/htdocs/wp-content/themes/basey/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:310:12)
  at Module.require (module.js:365:17)
  at require (module.js:384:17)
  at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
  at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
  at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
  at /usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:159:9
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:79:12
  at /usr/local/lib/node_modules/gulp/node_modules/v8flags/index.js:35:7
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3

**Comment by zslabs** [comment]
Have you run npm update lately?
